-- TABLE 1
CREATE TABLE IF NOT EXISTS T4_CUSTOMER
(
	T4_CUST_ID INTEGER NOT NULL ,
	T4_CUST_FNAME VARCHAR(10) NOT NULL ,
	T4_CUST_LNAME VARCHAR(10) NOT NULL ,
	T4_CUST_DOB DATE NOT NULL ,
	T4_CUST_GENDER CHAR(2) NOT NULL ,
	T4_CUST_ADDRESS VARCHAR(20) NOT NULL ,
	T4_CUST_MOB_NUMBER VARCHAR(10) NOT NULL ,
	T4_CUST_EMAIL VARCHAR(20) NOT NULL ,
    T4_CUST_PASSPORT_NUMBER VARCHAR(20) NOT NULL ,
    T4_CUST_MARITAL_STATUS CHAR(10) NOT NULL ,
	T4_CUST_PPS_NUMBER INTEGER NOT NULL ,
    CONSTRAINT T4_XPKCUSTOMER_1 PRIMARY KEY (T4_CUST_ID)
);

-- TABLE 2
CREATE TABLE IF NOT EXISTS T4_INCIDENT
(
	T4_INCIDENT_ID VARCHAR(20) NOT NULL ,
	T4_INCIDENT_TYPE VARCHAR(30) NOT NULL ,
	T4_INCIDENT_DATE DATE NOT NULL ,
	T4_DESCRIPTION VARCHAR(100) NOT NULL ,
	CONSTRAINT T4_XPKINCIDENT_17 PRIMARY KEY (T4_INCIDENT_ID)
);

-- TABLE 3
CREATE TABLE IF NOT EXISTS T4_INCIDENT_REPORT
(
	T4_INCIDENT_REPORT_ID VARCHAR(20) NOT NULL  ,
	T4_INCIDENT_TYPE CHAR(10) NOT NULL ,
	T4_INCIDENT_INSPECTOR VARCHAR(20) NOT NULL ,
	T4_INCIDENT_COST INTEGER NOT NULL ,
	T4_INCIDENT_REPORT_DESCRIPTION VARCHAR(100) NOT NULL ,
    T4_INCIDENT_ID VARCHAR(20) NOT NULL ,
    T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKINCIDENT_REPORT_18 PRIMARY KEY (T4_INCIDENT_REPORT_ID),
	CONSTRAINT T4_R_83 FOREIGN KEY (T4_INCIDENT_ID) REFERENCES T4_INCIDENT(T4_INCIDENT_ID) ON DELETE CASCADE,
	CONSTRAINT T4_R_86 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER(T4_CUST_ID) ON DELETE CASCADE
);

-- TABLE 4
CREATE TABLE IF NOT EXISTS T4_INSURANCE_COMPANY
(
	T4_COMPANY_NAME VARCHAR(20) NOT NULL ,
	T4_COMPANY_ADDRESS VARCHAR(20) NOT NULL ,
	T4_COMPANY_CONTACT_NUMBER VARCHAR(10) NOT NULL ,
	T4_COMPANY_FAX INTEGER NOT NULL ,
	T4_COMPANY_EMAIL VARCHAR(20) NOT NULL ,
	T4_COMPANY_WEBSITE VARCHAR(20) NOT NULL ,
	T4_COMPANY_LOCATION VARCHAR(20) NOT NULL ,
    T4_COMPANY_DEPARTMENT_NAME VARCHAR(20) NOT NULL ,
	T4_COMPANY_OFFICE_NAME VARCHAR(20) NOT NULL ,
	CONSTRAINT T4_XPKINSURANCE_COMPANY_15 PRIMARY KEY(T4_COMPANY_NAME,T4_COMPANY_DEPARTMENT_NAME)
);

-- TABLE 5
CREATE TABLE IF NOT EXISTS T4_DEPARTMENT
(
	T4_DEPARTMENT_NAME VARCHAR(20) NOT NULL ,
	T4_COMPANY_NAME VARCHAR(20) NOT NULL ,
	T4_OFFICE VARCHAR(18) NOT NULL ,
	T4_CONTACT_INFORMATION VARCHAR(30) NOT NULL,
	T4_DEPARTMENT_STAFF VARCHAR(18) NOT NULL ,
	T4_DEPARTMENT_LEADER VARCHAR(18) NOT NULL ,
	CONSTRAINT T4_XPKDEPARTMENT PRIMARY KEY (T4_DEPARTMENT_NAME),
	CONSTRAINT T4_R_56 FOREIGN KEY (T4_COMPANY_NAME,T4_DEPARTMENT_NAME) REFERENCES T4_INSURANCE_COMPANY (T4_COMPANY_NAME,T4_COMPANY_DEPARTMENT_NAME) ON UPDATE CASCADE
);

-- TABLE 6
CREATE TABLE IF NOT EXISTS T4_VEHICLE
(
	T4_VEHICLE_ID INTEGER NOT NULL ,
	T4_POLICY_ID VARCHAR(20) NOT NULL ,
	T4_DEPENDENT_NOK_ID VARCHAR(20) NOT NULL ,
	T4_VEHICLE_REGISTRATION_NUMBER VARCHAR(20) NOT NULL ,
	T4_VEHICLE_VALUE INTEGER NOT NULL ,
	T4_VEHICLE_TYPE VARCHAR(20) NOT NULL ,
	T4_VEHICLE_SIZE INTEGER NOT NULL ,
	T4_VEHICLE_NUMBER_OF_SEAT INTEGER NOT NULL ,
	T4_VEHICLE_MANUFACTURER VARCHAR(20) NOT NULL ,
	T4_VEHICLE_ENGINE_NUMBER INTEGER NOT NULL ,
	T4_VEHICLE_CHASIS_NUMBER INTEGER NOT NULL ,
	T4_VEHICLE_NUMBER VARCHAR(20) NOT NULL ,
	T4_VEHICLE_MODEL_NUMBER VARCHAR(20) NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKVEHICLE_6 PRIMARY KEY (T4_VEHICLE_ID),
	CONSTRAINT T4_R_92 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER(T4_CUST_ID) ON DELETE CASCADE
);

-- TABLE 7
CREATE TABLE IF NOT EXISTS T4_VEHICLE_SERVICE
(
	T4_VEHICLE_SERVICE VARCHAR(30) NOT NULL ,
	T4_VEHICLE_ID INTEGER NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	T4_DEPARTMENT_NAME VARCHAR(20) NOT NULL ,
	T4_VEHICLE_SERVICE_ADDRESS VARCHAR(20) NOT NULL ,
	T4_VEHICLE_SERVICE_CONTACT VARCHAR(20) NOT NULL ,
	T4_VEHICLE_SERVICE_INCHARGE VARCHAR(20) NOT NULL ,
	T4_VEHICLE_SERVICE_TYPE VARCHAR(20) NOT NULL ,
	T4_COMPANY_NAME VARCHAR(20) NOT NULL ,
	CONSTRAINT T4_XPKVEHICLE_SERVICE PRIMARY KEY(T4_VEHICLE_SERVICE),
	CONSTRAINT T4_R_50 FOREIGN KEY (T4_VEHICLE_ID) REFERENCES T4_VEHICLE(T4_VEHICLE_ID) ON DELETE CASCADE,
	CONSTRAINT T4_R_51 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER(T4_CUST_ID) ON DELETE RESTRICT 
);

-- TABLE 8
CREATE TABLE IF NOT EXISTS T4_PREMIUM_PAYMENT
(
	T4_PREMIUM_PAYMENT_ID VARCHAR(20) NOT NULL ,
	T4_POLICY_NUMBER VARCHAR(20) NOT NULL ,
	T4_PREMIUM_PAYMENT_AMOUNT INTEGER NOT NULL DEFAULT 0 ,
	T4_PREMIUM_PAYMENT_SCHEDULE DATE NOT NULL ,
	T4_RECEIPT_ID VARCHAR(20) NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKPREMIUM_PAYMENT_5 PRIMARY KEY(T4_PREMIUM_PAYMENT_ID),
	CONSTRAINT T4_R_85 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER(T4_CUST_ID) ON DELETE CASCADE
);

-- TABLE 9
CREATE TABLE IF NOT EXISTS T4_RECEIPT
(
	T4_RECEIPT_ID VARCHAR(20) NOT NULL ,
	T4_TIME DATE NOT NULL ,
	T4_COST INTEGER NOT NULL ,
	T4_PREMIUM_PAYMENT_ID VARCHAR(20) NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKRECEIPT_21 PRIMARY KEY(T4_RECEIPT_ID),
	CONSTRAINT T4_R_84 FOREIGN KEY (T4_PREMIUM_PAYMENT_ID) REFERENCES T4_PREMIUM_PAYMENT (T4_PREMIUM_PAYMENT_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT T4_R_88 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER ( T4_CUST_ID) ON UPDATE RESTRICT ON DELETE CASCADE
);

-- TABLE 10
CREATE TABLE IF NOT EXISTS T4_APPLICATION
(
	T4_APPLICATION_ID VARCHAR(20) NOT NULL ,
	T4_VEHICLE_ID INTEGER NOT NULL ,
	T4_APPLICATION_STATUS CHAR(8) NOT NULL ,
	T4_COVERAGE VARCHAR(50) NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKAPPLICATION_2 PRIMARY KEY(T4_APPLICATION_ID),
	CONSTRAINT T4_R_93 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER(T4_CUST_ID) ON UPDATE RESTRICT
);

-- TABLE 11
CREATE TABLE IF NOT EXISTS  T4_INSURANCE_POLICY
(
	T4_AGREEMENT_ID VARCHAR(20) NOT NULL ,
	T4_DEPARTMENT_NAME VARCHAR(20) NOT NULL ,
	T4_POLICY_NUMBER VARCHAR(20) NOT NULL ,
	T4_START_DATE DATE NOT NULL ,
	T4_EXPIRY_DATE DATE NOT NULL ,
	T4_TERM_CONDITION_DESCRIPTION VARCHAR(100) NOT NULL ,
	T4_APPLICATION_ID VARCHAR(20) NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKINSURANCE_POLICY_4 PRIMARY KEY(T4_AGREEMENT_ID),
	CONSTRAINT T4_R_95 FOREIGN KEY (T4_APPLICATION_ID) REFERENCES T4_APPLICATION (T4_APPLICATION_ID) ON DELETE CASCADE ,
    CONSTRAINT T4_R_96 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER (T4_CUST_ID) ON UPDATE RESTRICT
    
);

-- TABLE 12
CREATE TABLE IF NOT EXISTS T4_POLICY_RENEWABLE
(
	T4_POLICY_RENEWABLE_ID VARCHAR(20) NOT NULL ,
	T4_DATE_OF_RENEWAL DATE NOT NULL ,
	T4_TYPE_OF_RENEWAL CHAR(15) NOT NULL ,
	T4_AGREEMENT_ID VARCHAR(20) NOT NULL ,
	T4_APPLICATION_ID VARCHAR(20) NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKPOLICY_RENEWABLE_16 PRIMARY KEY(T4_POLICY_RENEWABLE_ID),
	CONSTRAINT T4_R_101 FOREIGN KEY (T4_AGREEMENT_ID)REFERENCES T4_INSURANCE_POLICY (T4_AGREEMENT_ID) ON DELETE CASCADE,
    CONSTRAINT T4_R_102 FOREIGN KEY (T4_APPLICATION_ID)REFERENCES T4_APPLICATION(T4_APPLICATION_ID) ON UPDATE CASCADE,
    CONSTRAINT T4_R_103 FOREIGN KEY (T4_CUST_ID)REFERENCES T4_CUSTOMER (T4_CUST_ID) ON UPDATE RESTRICT
);

-- TABLE 13
CREATE TABLE IF NOT EXISTS T4_MEMBERSHIP
(
	T4_MEMBERSHIP_ID VARCHAR(20) NOT NULL ,
	T4_MEMBERSHIP_TYPE CHAR(15) NOT NULL ,
	T4_ORGANISATION_CONTACT VARCHAR(20) NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKMEMBERSHIP_12 PRIMARY KEY(T4_MEMBERSHIP_ID),
	CONSTRAINT T4_R_91 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER(T4_CUST_ID) ON DELETE CASCADE
);

-- TABLE 14
CREATE TABLE IF NOT EXISTS T4_QUOTE
(
	T4_QUOTE_ID VARCHAR(20) NOT NULL ,
	T4_ISSUE_DATE DATE NOT NULL ,
	T4_VALID_FROM_DATE DATE NOT NULL ,
	T4_VALID_TILL_DATE DATE NOT NULL ,
	T4_DESCRIPTION VARCHAR(100) NOT NULL ,
	T4_PRODUCT_ID VARCHAR(20) NOT NULL ,
	T4_COVERAGE_LEVEL VARCHAR(20) NOT NULL ,
	T4_APPLICATION_ID VARCHAR(20) NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKQU0TE_3 PRIMARY KEY (T4_QUOTE_ID),
	CONSTRAINT T4_R_71 FOREIGN KEY (T4_APPLICATION_ID) REFERENCES T4_APPLICATION (T4_APPLICATION_ID) ON DELETE CASCADE,
	CONSTRAINT T4_R_72 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER(T4_CUST_ID) ON DELETE CASCADE 
);

-- TABLE 15
CREATE TABLE IF NOT EXISTS T4_STAFF
(
	T4_STAFF_ID VARCHAR(20) NOT NULL ,
	T4_STAFF_FNAME VARCHAR(10) NOT NULL ,
	T4_STAFF_LNAME VARCHAR(10) NOT NULL ,
	T4_STAFF_ADDRESS VARCHAR(20) NOT NULL ,
	T4_STAFF_CONTACT VARCHAR(10) NOT NULL ,
	T4_STAFF_GENDER CHAR(2) NOT NULL ,
	T4_STAFF_MARITAL_STATUS CHAR(10) NOT NULL ,
	T4_STAFF_NATIONALITY CHAR(15) NOT NULL ,
	T4_STAFF_QUALIFICATION VARCHAR(20) NOT NULL ,
	T4_STAFF_ALLOWANCE INTEGER NOT NULL ,
	T4_STAFF_PPS_NUMBER INTEGER NOT NULL ,
	T4_COMPANY_NAME VARCHAR(20) NOT NULL ,
	CONSTRAINT T4_XPKSTAFF_9 PRIMARY KEY (T4_STAFF_ID),
	CONSTRAINT T4_R_105 FOREIGN KEY (T4_COMPANY_NAME) REFERENCES T4_INSURANCE_COMPANY (T4_COMPANY_NAME) ON UPDATE CASCADE
);

-- TABLE 16
CREATE TABLE IF NOT EXISTS T4_NOK
(
   T4_NOK_ID VARCHAR(20) NOT NULL ,
   T4_NOK_NAME VARCHAR(20) NOT NULL ,
   T4_NOK_ADDRESS VARCHAR(20) NOT NULL , 
   T4_NOK_PHONE_NUMBER VARCHAR(10) NOT NULL ,
   T4_NOK_GENDER CHAR(2) NOT NULL ,
   T4_NOK_MARITAL_STATUS CHAR(10) NOT NULL ,
   T4_AGREEMENT_ID VARCHAR(20) NOT NULL ,
   T4_APPLICATION_ID VARCHAR(20) NOT NULL ,
   T4_CUST_ID INTEGER NOT NULL ,
   CONSTRAINT T4_XPKNOK_14 PRIMARY KEY (T4_NOK_ID),
   CONSTRAINT R_73 FOREIGN KEY (T4_AGREEMENT_ID) REFERENCES T4_INSURANCE_POLICY (T4_AGREEMENT_ID) ON DELETE CASCADE,
   CONSTRAINT R_74 FOREIGN KEY ( T4_APPLICATION_ID) REFERENCES T4_APPLICATION(T4_APPLICATION_ID) ON DELETE CASCADE,
   CONSTRAINT R_75 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER(T4_CUST_ID) ON UPDATE RESTRICT ON DELETE CASCADE
);

-- TABLE 17
CREATE TABLE IF NOT EXISTS T4_PRODUCT 
( 
	T4_PRODUCT_PRICE INTEGER NOT NULL ,
	T4_PRODUCT_TYPE CHAR(15) NOT NULL , 
	T4_PRODUCT_NUMBER VARCHAR(20) NOT NULL ,
	T4_COMPANY_NAME VARCHAR(20) NOT NULL ,
	CONSTRAINT T4_XPKPRODUCT_20 PRIMARY KEY (T4_PRODUCT_NUMBER), 
	CONSTRAINT T4_R_107 FOREIGN KEY (T4_COMPANY_NAME) REFERENCES T4_INSURANCE_COMPANY (T4_COMPANY_NAME) ON UPDATE CASCADE
);

-- TABLE 18
CREATE TABLE IF NOT EXISTS T4_OFFICE 
( 
	T4_OFFICE_NAME VARCHAR(20) NOT NULL , 
	T4_OFFICE_LEADER VARCHAR(20) NOT NULL , 
	T4_CONTACT_INFORMATION VARCHAR(20) NOT NULL , 
	T4_ADDRESS VARCHAR(20) NOT NULL ,
	T4_ADMIN_COST INTEGER NOT NULL , 
	T4_STAFF VARCHAR(50) NOT NULL , 
	T4_DEPARTMENT_NAME VARCHAR(20) NOT NULL , 
	T4_COMPANY_NAME VARCHAR(20) NOT NULL , 
	CONSTRAINT T4_XPKOFFICE_11 PRIMARY KEY (T4_OFFICE_NAME), 
	CONSTRAINT T4_R_110 FOREIGN KEY (T4_DEPARTMENT_NAME) REFERENCES T4_DEPARTMENT (T4_DEPARTMENT_NAME) ON DELETE CASCADE,
    CONSTRAINT T4_R_111 FOREIGN KEY (T4_COMPANY_NAME) REFERENCES T4_INSURANCE_COMPANY (T4_COMPANY_NAME) ON UPDATE CASCADE
);

-- TABLE 19
CREATE TABLE IF NOT EXISTS T4_COVERAGE
(
	T4_COVERAGE_ID VARCHAR(20) NOT NULL ,
	T4_COVERAGE_AMOUNT INTEGER NOT NULL ,
	T4_COVERAGE_TYPE CHAR(10) NOT NULL ,
	T4_COVERAGE_LEVEL CHAR(15) NOT NULL ,
	T4_PRODUCT_ID VARCHAR(20) NOT NULL ,
	T4_COVERAGE_DESCRIPTION VARCHAR(100) NOT NULL ,
	T4_COVEARGE_TERMS VARCHAR(50)  NOT NULL ,
	T4_COMPANY_NAME VARCHAR(20) NOT NULL ,
	CONSTRAINT T4_XPKCOVERAGE_19 PRIMARY KEY (T4_COVERAGE_ID),
	CONSTRAINT T4_R_112 FOREIGN KEY (T4_COMPANY_NAME) REFERENCES T4_INSURANCE_COMPANY (T4_COMPANY_NAME) ON UPDATE CASCADE
);

-- TABLE 20
CREATE TABLE IF NOT EXISTS T4_INSURANCE_POLICY_COVERAGE
(
	T4_AGREEMENT_ID VARCHAR(20) NOT NULL ,
	T4_COVERAGE_ID VARCHAR(20)NOT NULL ,
	CONSTRAINT T4_XPKINSURANCE_POLICY_4 PRIMARY KEY(T4_AGREEMENT_ID),
	CONSTRAINT T4_R_98 FOREIGN KEY (T4_COVERAGE_ID)REFERENCES T4_COVERAGE(T4_COVERAGE_ID) ON DELETE CASCADE
);

-- TABLE 21
CREATE TABLE IF NOT EXISTS T4_CLAIM 
( 
	T4_CLAIM_ID INTEGER NOT NULL ,
	T4_AGREEMENT_ID VARCHAR(20) NOT NULL , 
	T4_CLAIM_AMOUNT INTEGER NOT NULL , 
	T4_INCIDENT_ID VARCHAR(20) NOT NULL , 
	T4_DAMAGE_TYPE VARCHAR(20) NOT NULL , 
	T4_DATE_OF_CLAIM DATE NOT NULL ,
	T4_CLAIM_STATUS CHAR(10) NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKCLAIM_7 PRIMARY KEY (T4_CLAIM_ID),
	CONSTRAINT T4_R_115 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER(T4_CUST_ID) ON UPDATE RESTRICT
);

-- TABLE 22
CREATE TABLE IF NOT EXISTS T4_CLAIM_SETTLEMENT
(
	T4_CLAIM_SETTLEMENT_ID INTEGER NOT NULL ,
	T4_VEHICLE_ID INTEGER NOT NULL ,
	T4_DATE_SETTLED DATE NOT NULL ,
	T4_AMOUNT_PAID INTEGER NOT NULL ,
	T4_COVERAGE_ID VARCHAR(20) NOT NULL ,
	T4_CLAIM_ID INTEGER NOT NULL ,
	T4_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T4_XPKCLAIM_SETTLEMENT_8 PRIMARY KEY(T4_CLAIM_SETTLEMENT_ID),
	CONSTRAINT T4_R_120 FOREIGN KEY (T4_CLAIM_ID) REFERENCES T4_CLAIM(T4_CLAIM_ID) ON DELETE CASCADE,
	CONSTRAINT T4_R_121 FOREIGN KEY (T4_CUST_ID) REFERENCES T4_CUSTOMER(T4_CUST_ID) ON DELETE CASCADE
);
